org.gradle.jvmargs=-Xmx6G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
net.minecraftforge.gradle.merge-source-sets=true
minecraft_version=26.2
minecraft_next_version=26.3
forge_version=65.1.0
forge_spec_version=65
eventbus_version=7.0.5
java_version=25
